# Generated by Django 6.0.7 on 2026-07-28 06:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacao',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='imovel',
            name='anfitriao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imoveis', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='imovel',
            name='comodidades',
            field=models.ManyToManyField(blank=True, related_name='imoveis', to='core.comodidade'),
        ),
        migrations.AddField(
            model_name='imagemimovel',
            name='imovel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='core.imovel'),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='imovel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='core.imovel'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='hospede',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reserva',
            name='imovel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='core.imovel'),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='reserva',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacao', to='core.reserva'),
        ),
    ]
